### ISSUE TITLE
Can we Extend this code to make it a receiver spoofer?

### ISSUE THREAD

**Issue by Imtiaz08** [unalfaruk/SoftGNSS#2]
Hi Unalfaruk, 

Brother, I hope this message finds you in the best health. I know you must be a busy person as I have been through my masters thesis and have an idea how hectic it can be. I was studying the SOFTGNSS code and was wondering if we can turn the receiver into a reciever spoofer architecture. 

What I want to say is we record an IF signal using an RTL SDR device, read it through the SoftGNSS and change the parameters such as code phases and doppler phase shift to turn it into a spoofing signal. 

What do you thing about this idea? we can work together on this if you want.

**Comment by unalfaruk** [comment]
Dear @Imtiaz08,

Thanks for texting to me.

Your idea is so great! Theoretically it is possible of course, however it is a different major task from designing a receiver and its architecture.

The task will be doing the opposite things what a receiver does. I mean modulation instead of demodulation, encoding instead of decoding etc. 

To sum up, it is like a SIMULATOR, but not fully functional. There are a few GitHub repositories for spoofer (with HackRF and other dongles) and simulator (with HackRF again). You should analyze them, it may seem difficult but your idea require a part of their implementations, you won’t generate new navigation data, will just manipulate, encode and modulate. But please don’t assume these tasks so easy :)

I would like to help you or work together, but nowadays I have a few serious change in my life, new job, new city etc. So, I am so sad, I can not. But whenever you need, we can do brainstorm, discuss 👍🏾
